//////////////////////////// Primitive Data //////////////////////////
// Primitive data types in JavaScript include:
// Numbers - Integers, floats
// Strings - Any data under single quote, double quote or backtick quote
// Booleans - true or false value
// Null - empty value or no value
// Undefined - a declared variable without a value
// Symbol - A unique value that can be generated by Symbol constructor

// Non-primitive data types in JavaScript includes: //modifiable or mutable
// Objects
// Arrays
//Functions

//Primitive Data Types are immutable (non-modifyable) You can't change them
// let word = "JavaScript" //this variable has been declared and defined/
//word = "Python"  //You do not have to redeclare the variable, just reassign the value of it
// word[0]="y"

<<<<<<< HEAD

let numOne=3;
let numTwo="3"
console.log(numOne== numTwo)
=======
//Boolean
// let numOne = 3;
// let numTwo ="3"
// console.log(numOne == numTwo)  //returns a true or false value
>>>>>>> 85516a09f272ecc1d5bd2dd78e4730a95610fdca

// let js ="javascript"
// let py ="python"
// console.log(js == python)

//Non-Primitive Data Types are mutable (you can change them)
//an 
// let number=[1,2,3]
// number[0]=11
// console.log(number)


//Object
// let car2={
//     color: "Blue"
// }
// console.log(car1==car2)